apiVersion: v1
items:
- apiVersion: cert-manager.io/v1
  kind: ClusterIssuer
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cert-manager.io/v1","kind":"ClusterIssuer","metadata":{"annotations":{},"name":"selfsigned-issuer"},"spec":{"selfSigned":{}}}
    creationTimestamp: "2025-10-02T11:33:48Z"
    generation: 1
    name: selfsigned-issuer
    resourceVersion: "391796"
    uid: a02c5bf7-f87c-4dc6-9c59-8e0dedfd5f21
  spec:
    selfSigned: {}
  status:
    conditions:
    - lastTransitionTime: "2025-10-02T11:33:48Z"
      observedGeneration: 1
      reason: IsReady
      status: "True"
      type: Ready
kind: List
metadata:
  resourceVersion: ""
